version: '3'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-app
        tty: true
        command: tail -f /dev/null
        volumes:
            - ./app:/home/gradle
        networks:
            - backend-admin-video-catalog-network
        depends_on:
            - db

    db:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: backend-admin-video-catalog-db
        tty: true
        ports:
            - "33062:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=backend-admin-video-catalog
            - MYSQL_ROOT_PASSWORD=root
        security_opt:
            - seccomp:unconfined
        networks:
            - backend-admin-video-catalog-network

networks:
    backend-admin-video-catalog-network:
        driver: bridge
