# arquivo com configurações adicionais que sobrescrevem às do arquivo principal application.yml, no profile development

# configurações do servidor
server:
  undertow:
    threads: # configurando as threads do servidor
      worker: 10 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 2 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

# configurações do mysql
mysql: # bd
  username: root
  password: root
  schema: backend-admin-video-catalog
#  url: localhost:33062 # utilizada para subir pela ide
  url: db:3306 # utilizada para subir pelo container